from __future__ import annotations

import secrets
import sqlite3
import time
import uuid
from pathlib import Path


def safe_filename(filename: str) -> str:
    name = filename.replace("\\", "_").replace("/", "_").replace("\x00", "")
    name = "".join(char for char in name if char.isprintable()).strip(" .")
    return (name or "download")[:180]


class FileStore:
    def __init__(self, data_dir: Path, *, ttl_hours: int) -> None:
        self.data_dir = data_dir
        self.data_dir.mkdir(parents=True, exist_ok=True)
        self.db_path = self.data_dir / "links.sqlite3"
        self.ttl_seconds = ttl_hours * 60 * 60
        with self._connect() as connection:
            connection.execute(
                """CREATE TABLE IF NOT EXISTS files (
                    token TEXT PRIMARY KEY,
                    stored_name TEXT NOT NULL UNIQUE,
                    filename TEXT NOT NULL,
                    size INTEGER NOT NULL,
                    content_type TEXT NOT NULL,
                    owner_id INTEGER NOT NULL,
                    created_at INTEGER NOT NULL
                )"""
            )

    def _connect(self) -> sqlite3.Connection:
        connection = sqlite3.connect(self.db_path, timeout=10)
        connection.row_factory = sqlite3.Row
        return connection

    def new_path(self) -> Path:
        return self.data_dir / f"{uuid.uuid4().hex}.blob"

    def register(self, *, path: Path, filename: str, size: int, content_type: str, owner_id: int) -> str:
        self.cleanup_expired()
        token = secrets.token_urlsafe(24)
        with self._connect() as connection:
            connection.execute(
                "INSERT INTO files(token, stored_name, filename, size, content_type, owner_id, created_at) "
                "VALUES (?, ?, ?, ?, ?, ?, ?)",
                (token, path.name, safe_filename(filename), size, content_type, owner_id, int(time.time())),
            )
        return token

    def get(self, token: str) -> dict | None:
        with self._connect() as connection:
            row = connection.execute(
                "SELECT token, stored_name, filename, size, content_type, owner_id, created_at "
                "FROM files WHERE token = ?",
                (token,),
            ).fetchone()
        if row is None:
            return None
        item = dict(row)
        if int(time.time()) - item["created_at"] >= self.ttl_seconds:
            self.delete(token)
            return None
        return item

    def path_for(self, item: dict) -> Path:
        # The stored name is generated by new_path, never taken from the upload filename.
        return self.data_dir / item["stored_name"]

    def delete(self, token: str) -> None:
        with self._connect() as connection:
            row = connection.execute("SELECT stored_name FROM files WHERE token = ?", (token,)).fetchone()
            if row is None:
                return
            connection.execute("DELETE FROM files WHERE token = ?", (token,))
        (self.data_dir / row["stored_name"]).unlink(missing_ok=True)

    def cleanup_expired(self) -> None:
        cutoff = int(time.time()) - self.ttl_seconds
        with self._connect() as connection:
            rows = connection.execute("SELECT token FROM files WHERE created_at <= ?", (cutoff,)).fetchall()
        for row in rows:
            self.delete(row["token"])

